### ISSUE TITLE
some matter occurs when run the evaluate  

### ISSUE THREAD

**Issue by GL123456** [WSPTTH/SREPS#1]
(SREPS) F:\SREPS-master\SREPS-master>python main.py --mode=eval --dev_file=F\filmtrust\dev  --save_path=model\model.npz
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    res = model.eval([dev_data])
  File "F:\SREPS-master\SREPS-master\model.py", line 234, in eval
    for name, dataset in evals:
TypeError: 'Dataset' object is not iterable

**Comment by GL123456** [comment]
> (SREPS) F:\SREPS-master\SREPS-master>python main.py --mode=eval --dev_file=F\filmtrust\dev --save_path=model\model.npz
> Traceback (most recent call last):
> File "main.py", line 59, in
> res = model.eval([dev_data])
> File "F:\SREPS-master\SREPS-master\model.py", line 234, in eval
> for name, dataset in evals:
> TypeError: 'Dataset' object is not iterable

How do I modify it to make it work？Hope to get your help! Thanks

**Comment by WSPTTH** [comment]
you may try to add a name for the evaluation dataset as 
```
res = model.eval([('eval', dev_data)])
```

**Comment by GL123456** [comment]
> you may try to add a name for the evaluation dataset as
> 
> ```
> res = model.eval(['eval', dev_data])
> ```

is that add it at main.py ?  I modified it this way, but there are still some problems here.  
*** ***  ***
(SREPS) F:\SREPS-master\SREPS-master>python main.py --mode=eval --dev_file=F\filmtrust\dev  --save_path=model\model.npz
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    res = model.eval(['eval', dev_data])
  File "F:\SREPS-master\SREPS-master\model.py", line 238, in eval
    for name, dataset in evals:
ValueError: too many values to unpack (expected 2)

**Comment by GL123456** [comment]
&nbsp;Sorry to bother you, but I still encounter many problems in my attempt to modify.&nbsp;
&nbsp; Sincerely hope to get your assistance!&nbsp; &nbsp;Thank you very&nbsp; much !







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WSPTTH/SREPS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月31日(星期一) 下午3:40
收件人:&nbsp;"WSPTTH/SREPS"<SREPS@noreply.github.com&gt;;
抄送:&nbsp;"岁也"<694045516@QQ.COM&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WSPTTH/SREPS] some matter occurs when run the evaluate   (#1)





 
you may try to add a name for the evaluation dataset as
 res = model.eval(['eval', dev_data])

**Comment by GL123456** [comment]
Sorry to bother you, but I still encounter many problems when I try to modify it!   Sincerely hope to get your help.  Thank you very much!

**Comment by WSPTTH** [comment]
I forget to make the (name, dataset) tuple, you can try this:
```
res = model.eval([ ('eval', dev_data) ])
```

**Comment by GL123456** [comment]
> I forget to make the (name, dataset) tuple, you can try this:
> 
> ```
> res = model.eval([ ('eval', dev_data) ])
> ```

The matter has been settled. Thank you for your kindness！
